PiBox/PiHome/PiApp/urls.py
#coding=utf-8
'''
# The code in this file will modify url and register pci list

# Any issues or improvements please contact jacob-chen@iotwrt.com
'''

from django.conf.urls import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from views import *
from common import globaldata
import sys,os

'''
    default display url
'''
urlpatterns = patterns('',)

cwd  = globaldata.APP_DIR
list = os.listdir(cwd)
sys.path.append(cwd);
for item in list:
    if os.path.isdir(os.path.join(cwd, item)):
        urlpatterns += patterns ('',
            (r'^app/' + item + '/', include(item + '.urls')),
            )

urlpatterns += patterns('',
    (r'^$', dashboard),
    (r'^dashboard/$', dashboard),
    (r'^notification/$', notification_view),

    (r'^settings/account/$', settings_account_view),
    (r'^settings/general/$', settings_general_view),

    (r'^status/default/$', status_default_view),
    (r'^status/about/$', status_about_view),
    (r'^status/dmesg/$', status_dmesg_view),
    (r'^status/process/$', status_process_view),

    (r'^nas/file/$', nas_file_view),
    (r'^nas/video/$', nas_video_view),
    (r'^nas/download/$', nas_download_view),

    (r'^webssh/$', webssh_view), 

    (r'^home/index/$', home_view),   
    (r'^home/help/$', home_help_view),   
    (r'^home/help/en$', home_help_en_view),
    (r'^home/add_home/$', add_home_view),
    (r'^home/device/$', device_view), 
    (r'^home/add_device/$', add_device_view),  
    (r'^home/edit_device/$', edit_device_view),  
    (r'^home/manage_device/$', manage_device_view),  
    (r'^home/add_sensor/$', add_sensor_view),  
    (r'^home/edit_sensor/$', edit_sensor_view), 
    (r'^home/sensor_data/$', sensor_data_view), 
)


'''
    register pihome control interface list,will be used to create sidebar and titlebar 
'''    
pci_list = globaldata.pci_list
#register dashboard to pci list
pci_list.register('dashboard', "/PiApp/dashboard/", 'fa-dashboard')

#register App list to pci list
pci_list.register('application', '', 'fa-folder')
list = os.listdir(globaldata.APP_DIR)
for item in list:
    if os.path.isdir(os.path.join(globaldata.APP_DIR, item)):
        name = globaldata.app_ini.read(item, 'Name')
        pci_list.addchild(name, "/PiApp/app/" + item, 'application')


pci_list.register('my house', "/PiApp/home/index/", 'fa-home')        
pci_list.addchild('home', "/PiApp/home/index/", 'my house')
pci_list.addchild('add device', "/PiApp/home/add_device/", 'my house')
pci_list.addchild('manage device', "/PiApp/home/manage_device/", 'my house')
pci_list.addchild('document', "/PiApp/home/help/", 'my house')

pci_list.register('nas', "/PiApp/nas/file/", 'fa-hdd-o')       
pci_list.addchild('fileBrowser', "/PiApp/nas/file/", 'nas')
pci_list.addchild('download', "/PiApp/nas/download/", 'nas')

pci_list.register('SSH', "/PiApp/webssh/", 'fa-laptop')       

pci_list.register('status', "/PiApp/status/default/", 'fa-bar-chart-o')       
pci_list.addchild('default', "/PiApp/status/default/", 'status')
pci_list.addchild('kernel log', "/PiApp/status/dmesg/", 'status')
pci_list.addchild('process', "/PiApp/status/process/", 'status')
pci_list.addchild('about', "/PiApp/status/about/", 'status')

pci_list.register('settings', "/PiApp/settings/general/", 'fa-cog')       
pci_list.addchild('general', "/PiApp/settings/general/", 'settings')
pci_list.addchild('account', "/PiApp/settings/account/", 'settings')

   

PiBox/PiHome/PiHome/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from PiApp.views import *
from PiApp.api import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings 
from django.conf.urls.static import static

from common import globaldata
import os
import sys

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'PiHome.views.home', name='home'),,
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/login/$', login_view),
    (r'^accounts/logout/$', logout_view),
    (r'^accounts/register/$', register_view),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += patterns ('',
    (r'^$', include('PiApp.urls')),
    (r'^PiApp/', include('PiApp.urls')),
    (r'^filemanager/', include('filemanager.urls')),
    (r'^API/', include('PiApp.api_urls')),
)

if settings.DEBUG is False:
    urlpatterns += patterns('',
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT,
        }),
   )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'PiApp.views.fzf_view'
handler500 = 'PiApp.views.fzz_view'

PiBox/PiHome/filemanager/urls.py
from django.conf.urls import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from filemanager import path_end
from views import *

urlpatterns = patterns('',
    (r''+path_end, index),
)

PiBox/PiHome/PiApp/models.py
#coding=utf-8
'''
# The modules contains PiApp's models 

# Any issues or improvements please contact jacob-chen@iotwrt.com
'''

from django.db import models
from django.contrib.auth.models import AbstractUser
from PiHome import settings

import os

UPLOAD_ROOT = 'pibox_upload'
UPLOAD_ROOT_HOUSR_PLAN='pibox_upload/house_plan/'
UPLOAD_ROOT_PIC='pibox_upload/pic_datapoint/'


class PiUser(AbstractUser):
    new_field = models.CharField(max_length=100)


class PiSettings(models.Model):
    ip       = models.GenericIPAddressField(default="127.0.0.1")
    port     = models.IntegerField(default=3333)
    enable_register = models.BooleanField(default=True)


"""
    my house model
"""
class Device(models.Model):
    name = models.CharField(max_length=30)
    describe = models.TextField(default='')
    location = models.CharField(max_length=100)
    x = models.FloatField()
    y = models.FloatField()            

class Home(models.Model):
    name = models.CharField(max_length=100)
    img = models.ImageField(upload_to = UPLOAD_ROOT_HOUSR_PLAN)

SENSORCHOICE = (
 ('s', 'switch'),
 ('n', 'numeric'),
 ('p', 'picture'),
)
CONDITIONCHOICE = (
 ('lt', 'less than'),
 ('lte', 'less than or equal'),
 ('gt', 'greater than'),
 ('gte', 'greater than or equal'),
 ('ne', 'not equal'),
 ('e', 'equal'),
)
class Sensor(models.Model):
    device = models.ForeignKey(Device, related_name="sensor")  #books = author.books.all()
    name = models.CharField(max_length=100)
    describe = models.TextField(default='')
    sensor_class = models.CharField(max_length=1, choices=SENSORCHOICE)    
    unit = models.CharField(max_length=20, blank=True)
    callback_value = models.FloatField(default=0)
    callback_condition = models.CharField(max_length=3, blank=True, choices=CONDITIONCHOICE)
    callback_file = models.CharField(max_length=120, blank=True)


class SwitchDatapoint(models.Model):    
    sensor = models.ForeignKey(Sensor, unique=True)  
    status = models.BooleanField(default=False)
class NumDatapoint(models.Model):  
    sensor = models.ForeignKey(Sensor)  
    #yyyy-MM-dd HH:mm:ss
    key = models.DateTimeField(unique=True)
    value = models.FloatField()   
class PicDatapoint(models.Model):  
    sensor = models.ForeignKey(Sensor)  
    #yyyy-MM-dd HH:mm:ss
    key = models.DateTimeField(unique=True)
    pic_file = models.ImageField(upload_to = UPLOAD_ROOT_PIC) 


"""
    others
"""
TYPECHOICE = (
 ('d', 'danger'),
 ('i', 'info'),
 ('w', 'warning'),
)

class Notification(models.Model):
    """消息通知类
    """
    type = models.CharField(max_length=1, choices=TYPECHOICE)
    ## 0 for all
    user_id = models.IntegerField(db_index=True, default=0)
    title = models.TextField(default='')
    content = models.TextField(default='')
    has_readed = models.BooleanField(default=False)

PiBox/PiHome/templates/home/add.html
{% extends "base-user.html" %}

{% block css%}    
{% endblock %}
{% block js%}  
<script>
$(function() {
    $('#house-plan').click(function(e){
        var offset = $(this).offset();
        var relativeX = (e.pageX - offset.left)/$(this).width() * 100;
        var relativeY = (e.pageY - offset.top)/$(this).height() * 100;
        $('#id_x').val(Math.round(relativeX*1000)/1000);
        $('#id_y').val(Math.round(relativeY*1000)/1000);
        // alert('x' + e.screenX  + 'y' + e.screenY );
    });
})  
</script>
{% endblock %}

{% block on_ready%}    
{% endblock %}

{% block content %} 
<div class="row">      
    <div class="col-md-12">
        <div class="box box-solid box-navy ">
            <div class="box-header">
                <i class="fa fa-plus"></i>
                <h3 class="box-title">Device</h3>
            </div><!-- /.box-header -->
            <form action="" method="POST">
                <div class="box-body  ">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Device Name</label>
                        <p class="help-block">Get a name for your device,no more than 30 chars</p>
                        {{form.name}} 
                        {{form.name.errors}} 
                    </div>
                    <label for="id_describe">Describe</label>
                    <div class="form-group django-form">                       
                        {{form.describe}} 
                        {{form.describe.errors}} 
                    </div>
                    <div class="form-group">
                        <label for="id_location">Location</label>
                        <p class="help-block">Like : Bathroom</p>
                        {{form.location}} 
                        {{form.location.errors}} 
                    </div>
                    <div class="form-group django-form">
                        <div class="row">
                            <div class="col-lg-6">
                                <label for="id_x">X(%)</label>
                                {{form.x}} 
                                {{form.x.errors}} 
                            </div>
                            <div class="col-lg-6">
                                <label for="id_y">Y(%)</label>
                                {{form.y}} 
                                {{form.y.errors}} 
                            </div>
                        </div>                                
                    </div>
                    <div>
                        <img id="house-plan" class="house-plan" src="{{ img_url }}"></img>
                    </div>
                    <!-- <div class="form-group">
                        <label>Select Multiple</label>
                        <select class="form-control">
                            <option>option 1</option>
                            <option>option 2</option>
                            <option>option 3</option>
                            <option>option 4</option>
                            <option>option 5</option>
                        </select>
                    </div> -->

                </div><!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div><!-- /.box -->
    </div>
</div>	
{% endblock %}

PiBox/PiHome/templates/home/add_home.html
{% extends "base-user.html" %}

{% block css%}    
{% endblock %}
{% block js%}    
{% endblock %}

{% block on_ready%}    
{% endblock %}

{% block content %} 
<div class="row">      
    <div class="col-md-12">
        <div class="box box-solid box-navy ">
            <div class="box-header">
                <i class="fa fa-home"></i>
                <h3 class="box-title">Home</h3>  
                <div class="box-tools pull-right">
                    <a class="btn btn-navy" href="{% url 'PiApp.views.home_view' %}" style="color:#fff;")><i class="fa fa-long-arrow-left"></i></a>
                </div>              
            </div><!-- /.box-header -->
            <form action="" method="POST" enctype="multipart/form-data">
                <div class="box-body">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Name</label>
                        {{form.name}}
                        {{form.name.errors}} 
                    </div>
                    <div class="form-group">
                        <label for="id_img">House plan</label>
                        <p class="help-block">Get a picture for your house(1000*1000 is better)</p>
                        {{form.img}}
                        {{form.img.errors}} 
                    </div>
                    <div>
                        <img class="house-plan" src="{{ img_url }}"></img>
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>  
</div>
{% endblock %}

PiBox/PiHome/templates/home/add_sensor.html
{% extends "base-user.html" %}

{% block css%}    
{% endblock %}
{% block js%}  
<script>
$(function() {
    if($('#id_sensor_class').val() != 'n')
        $('#form-unit').css('display', 'None');
    else
        $('#form-unit').css('display', 'block');
    $('#id_sensor_class').change(function(){
        if($('#id_sensor_class').val() != 'n')
            $('#form-unit').css('display', 'None');
        else
            $('#form-unit').css('display', 'block');
    });
});
</script>
{% endblock %}


{% block on_ready%}    
{% endblock %}

{% block content %} 
<div class="row">      
    <div class="col-md-12">
        <div class="box box-solid box-navy ">
            <div class="box-header">
                <h3 class="box-title">Sensor</h3>
            </div><!-- /.box-header -->
            <form action="" method="POST">
                <div class="box-body  ">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Sensor Name</label>
                        {{form.name}} 
                        {{form.name.errors}} 
                    </div>
                    <label for="id_describe">Describe</label>
                    <div class="form-group">
                        {{form.describe}} 
                        {{form.describe.errors}} 
                    </div>
                    <div class="form-group">
                        <label for="id_sensor_class">Sensor Class</label>
                        {{form.sensor_class}} 
                        {{form.sensor_class.errors}} 
                    </div>
                    <div id="form-unit"class="form-group" style="display:None;">
                        <label for="id_unit">Unit</label>
                        <p class="help-block">Like : ℃</p>
                        {{form.unit}} 
                        {{form.unit.errors}}                           
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div><!-- /.box -->
    </div>
</div>	
{% endblock %}

PiBox/PiHome/templates/home/device.html
{% extends "base-no-sidebar.html" %}

{% block css%}    
<link href="/static/css/morris/morris.css" rel="stylesheet" type="text/css" />    
{% endblock %}

{% block js%} 
<script src="/static/js/plugins/raphael-min.js"></script>
<script src="/static/js/plugins/morris/morris.min.js" type="text/javascript"></script>
<script type="text/javascript">
$(function() {

{% for sensor in sensors %}
    {% if sensor.sensor_class == 's' %}
        switch_refresh({{sensor.id}});
    {% endif %}
    {% if sensor.sensor_class == 'n' %}
        curvet_refresh({{sensor.id}}, '{{sensor.unit}}');
    {% endif %}
    {% if sensor.sensor_class == 'p' %}
        img_refresh({{sensor.id}});
    {% endif %}
{% endfor %}

})



function switch_refresh(get_id){
    $.getJSON("/API/sensor/" + get_id + '/datapoint/get/',  {}, 
        function(data){
            if(data['msg'] != 'ok') {
                alert('failed');
            } else {
                if(data['value'] == 1) {
                    $("#btn-close" + get_id).attr('class', 'btn btn-default btn-lg');
                    $("#btn-open" + get_id).attr('class', 'btn btn-primary btn-lg active');  
                } else {
                    $("#btn-close" + get_id).attr('class', 'btn btn-primary btn-lg active');
                    $("#btn-open" + get_id).attr('class', 'btn btn-default btn-lg');                                          
                }
                    
            }               
    });  
}
function switch_open(get_id){
    $("#btn-close" + get_id).attr('class', 'btn btn-default btn-lg');
    $("#btn-open" + get_id).attr('class', 'btn btn-primary btn-lg active');    
    $.getJSON("/API/sensor/" + get_id + '/datapoint' ,  {value : 1}, 
        function(data){
            if(data['msg'] != 'ok') {
                alert('failed');
            }                
    });
}
function switch_close(get_id){
    $("#btn-close" + get_id).attr('class', 'btn btn-primary btn-lg active');
    $("#btn-open" + get_id).attr('class', 'btn btn-default btn-lg'); 
    $.getJSON("/API/sensor/" + get_id + '/datapoint' ,  {value : 0}, 
        function(data){
            if(data['msg'] != 'ok') {
                alert('failed');
            }                 
    });  
}
function curvet_refresh(get_id, unit){
    $.getJSON("/API/sensor/" + get_id + '/datapoint/history/',  {}, 
        function(data2){
            if(data2['msg'] != 'ok') {
                alert('failed');
            } else {
                var area = new Morris.Area({
                    element: "revenue-chart-" + get_id,
                    resize: true,
                    data: data2['datapoint'],
                    xkey: 'key',
                    ykeys: ['value'],
                    labels: ['value'],
                    // xLabels: [''],
                    postUnits : unit,
                    lineColors: ['#3c8dbc'],
                    hideHover: 'auto'
                });                              
            }               
    });                     
}
function img_refresh(get_id){
    $.getJSON("/API/sensor/" + get_id + '/datapoint/history/',  {}, 
        function(data){
            if(data['msg'] != 'ok') {
                // alert('failed');
            } else {
                for(var n=0; n < data['datapoint'].length; n++){
                    var content;
                    if(n == 0) {
                        content = '<div class="item active">'                        
                    }
                    else{
                        content = '<div class="item">'                             
                    }                  
                    content += '<center><img src="' + data['datapoint'][n]['value'] + '"></center>\
                                <div class="carousel-caption">\
                                    <h4 style="color:#fff;">Time</h4>\
                                    <p style="color:#fff;">' + data['datapoint'][n]['key'] + '</p> \
                                </div>\
                              </div>' 
                    $('.carousel-inner[sensor_id=' + get_id + ']').append(content);   
                }                                
            }               
    });                           
}
</script>   
{% endblock %}

{% block on_ready%}    
{% endblock %}

{% block content %} 

<p><b>Name:</b>{{device_instance.name}}</p>
<p><b>Describe:</b>{{device_instance.describe}}</p>
<p><b>Location:</b>{{device_instance.location}}</p>

{% for sensor in sensors %}  
<div class="callout callout-info">
    
    {% if sensor.sensor_class == 's' %}
    <p><b>Name:</b>{{sensor.name}}</p>
    <div class="btn-group" data-toggle="btn-toggle">
        <button id="btn-open{{sensor.id}}" style="height:100px;width:180px;" type="button" class="btn btn-default btn-lg" onclick="switch_open({{sensor.id}})"><span class="glyphicon glyphicon-play"></span></button>
        <button id="btn-close{{sensor.id}}" style="height:100px;width:180px;" type="button" class="btn btn-primary btn-lg active" onclick="switch_close({{sensor.id}})"><span class="glyphicon glyphicon-pause"></span></button>
    </div>
    {% endif %}
    {% if sensor.sensor_class == 'n' %}
    <a href="{% url 'PiApp.views.sensor_data_view' %}?sensor_id={{sensor.id}}"  style="float:right;">more here</a>
    <p><b>Name:</b>{{sensor.name}}</p>
    <div class="chart-responsive" style=""><div class="chart" id="revenue-chart-{{sensor.id}}" style="height: 250px;"></div></div>
    {% endif %}
    {% if sensor.sensor_class == 'p' %}
    <a href="{% url 'PiApp.views.sensor_data_view' %}?sensor_id={{sensor.id}}" style="float:right;">more here</a>
    <p><b>Name:</b>{{sensor.name}}</p>
    <div class="carousel slide" id="carousel-506941">
        <div sensor_id='{{sensor.id}}' class="carousel-inner">
        </div>
        <a class="left carousel-control" href="#carousel-506941" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#carousel-506941" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
    {% endif %}
</div>
{% endfor %}

{% endblock %}

<!-- <div class="col-md-6 col-md-offset-3"></div>   -->

PiBox/PiHome/templates/home/edit_sensor.html
{% extends "base-user.html" %}

{% block css%}    
{% endblock %}
{% block js%}  
<script>
$(function() {
    if($('#id_sensor_class').val() != 'n')
        $('#form-unit').css('display', 'None');
    else
        $('#form-unit').css('display', 'block');
    $('#id_sensor_class').change(function(){
        if($('#id_sensor_class').val() != 'n')
            $('#form-unit').css('display', 'None');
        else
            $('#form-unit').css('display', 'block');
    });
});
</script>
{% endblock %}


{% block on_ready%}    
{% endblock %}

{% block content %} 
<div class="row">      
    <div class="col-md-12">
        <div class="box box-solid box-navy ">
            <div class="box-header">
                <h3 class="box-title">Sensor</h3>
            </div><!-- /.box-header -->
            <form action="" method="POST">
                <div class="box-body  ">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_name">Sensor Name</label>
                        {{form.name}} 
                        {{form.name.errors}} 
                    </div>
                    <label for="id_describe">Describe</label>
                    <div class="form-group">
                        {{form.describe}} 
                        {{form.describe.errors}} 
                    </div>
                    <div class="form-group"  style="display:None;">
                        <label for="id_sensor_class">Sensor Class</label>
                        {{form.sensor_class}} 
                        {{form.sensor_class.errors}} 
                    </div>
                    <div id="form-unit"class="form-group" style="display:None;">
                        <label for="id_unit">Unit</label>
                        <p class="help-block">Like : ℃</p>
                        {{form.unit}} 
                        {{form.unit.errors}}                           
                    </div>
                </div><!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div><!-- /.box -->
    </div>
</div>	
{% endblock %}

PiBox/PiHome/templates/home/help_en.html
{% extends "base-user.html" %}

{% block css%}    
{% endblock %}
{% block js%}    
{% endblock %}


{% block on_ready%}    
{% endblock %}

{% block content %} 
<div class="row">      
    <div class="col-md-12">
        <div class="box box-solid box-navy ">
            <div class="box-header">
                <i class="fa fa-h-square"></i>
                <h3 class="box-title">Document-en</h3>
            </div><!-- /.box-header -->
            <div class="box-body  ">













            </div><!-- /.box-body -->

        </div><!-- /.box -->
    </div>
</div>
{% endblock %}

PiBox/PiHome/templates/home/home.html
{% extends "base-user.html" %}

{% block css%}    
{% endblock %}
{% block js%}    
<script type="text/javascript">
{% if home_exist %}

{% for device in device_all %}  
    var device{{forloop.counter}} = new Array();
    device{{forloop.counter}}['id']={{device.id}};
    device{{forloop.counter}}['name']='{{device.name}}'.substr(0,3) ;
    device{{forloop.counter}}['x']={{device.x}};
    device{{forloop.counter}}['y']={{device.y}};
{% endfor %}

$(window).load(function(){
    // $("#divId").offset(myOffset);
    

    {% for device in device_all %}  
    {
        var offset = $('.house-plan').offset();
        var relativeX = offset.left + $('.house-plan').width() * device{{forloop.counter}}['x'] / 100;
        var relativeY = offset.top + $('.house-plan').height() * device{{forloop.counter}}['y'] / 100;

        var content = get_device_content(device{{forloop.counter}});
        $("#home").append(content);
        $("div[sensor_id=" + device{{forloop.counter}}['id'] +']').css("position", "absolute");
        var div_offset = $("div[sensor_id=" + device{{forloop.counter}}['id'] +']').offset();

        div_offset.top = relativeY - $("div[sensor_id=" + device{{forloop.counter}}['id'] +']').height();
        div_offset.left = relativeX - $("div[sensor_id=" + device{{forloop.counter}}['id'] +']').width();
        $("div[sensor_id=" + device{{forloop.counter}}['id'] +']').offset(div_offset);
    }
    {% endfor %}

    $(".btn-device").click(function(){
        var id = $(this).attr("sensor_id");

        var content = '<iframe src="{% url "PiApp.views.device_view" %}?device_id=' + id + '" frameBorder="0" width="100%" height="400px" ></iframe>'
        $("#dialog").html(content);
        $("#dialog").attr("title", "Device");

        $("#dialog").dialog({
            modal: false,
            width:800, 
            buttons: {
                close: function() {
                    $(this).dialog("close");
                }, 
            },
        });

        $("#dialog").attr("width", "300px");
    });

})

function get_device_content(device){
    var content;
    content='<div class="btn-device btn btn-primary" sensor_id=' + device['id'] + ' style="border-radius: 50%; padding: 6px 6px;" >' + device['name'] + '</div>';

    return content;
}

{% endif %}  
</script>
{% endblock %}


{% block on_ready%}    
{% endblock %}


{% block content %} 
<div class="row">      
    <div id="home" class="col-md-12">
        <div class="box box-solid box-navy ">
            <div class="box-header">
                <i class="fa fa-home"></i>
                <h3 class="box-title">Overview</h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-navy" href="{% url 'PiApp.views.add_home_view' %}" style="color:#fff;")><i class="fa fa-edit"></i></a>
                </div>                
            </div><!-- /.box-header -->
            <div class="box-body  ">
                {% if home_exist %}
                <center>
                    <h4 class="page-header header-bold">
                        {{ home_instance.name }}                        
                    </h4>    
                </center>
                <img class="house-plan" src="{{ img_url }}"></img>
                {% else %}
                <div class="error-content">
                    <h3 ><i class="fa fa-edit"></i> 
                        <a href="{% url 'PiApp.views.add_home_view' %}">Fill up information.</a></h3>
                        <p>
                            No information is available for your home.
                        </p>
                </div><!-- /.error-content -->
                {% endif %}
            </div><!-- /.box-body -->
            <div class="box-footer">
            </div>
        </div>
    </div>
</div>	
{% endblock %}

PiBox/PiHome/templates/home/sensor_data.html
{% extends "base-user.html" %}

{% block css%}    
<!-- DATA TABLES -->
<link href="/static/css/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block js%}
<!-- DATA TABES SCRIPT -->
<script src="/static/js/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
<script src="/static/js/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>  
<script>
$(function() {
    $('#example1').dataTable();
});
</script>
{% endblock %}


{% block on_ready%}    
{% endblock %}

{% block content %} 
<div class="row">      
    <div class="col-md-12">

        <div class="box">
            <div class="box-header">
                <h3 class="box-title">{{get_sensor.name}} Data Table</h3>
            </div>
            <div class="box-body table-responsive">
                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>Datetime</th>
                            {% if get_sensor.sensor_class == 'n' %}
                            <th>Value</th>
                            {% else %}
                            <th>Url</th>
                            {% endif %}         
                        </tr>
                    </thead>
                    <tbody>
                    {%for item in datapoint%}
                    
                        <tr>
                            <td>{{item.key}}</td>
                            {% if get_sensor.sensor_class == 'n' %}
                            <td>{{item.value}} {{get_sensor.unit}}</td>
                            {% else %}
                            <td><a href="http://{{domain}}{{item.pic_file}}">{{domain}}{{item.pic_file}}</a></td>
                            {% endif %}         
                        </tr>
                    
                    {%endfor%}
                    </tbody>

                </table>
            </div>
        </div>

    </div>
</div>	
{% endblock %}